project_name: cli

before:
  hooks:
    - run: |
        cd ./cli
        go mod download

builds:
  - flags:
      - -buildmode=exe
    env:
      - GOGC=off
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./main.go
    ldflags:
      - -s -w -X github.com/stewartshea/cloudquery/cli/cmd.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: cloudquery

archives:
  -
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: binary

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
